#!/bin/bash

Contents=$(cat /home/mzarnoch/src/daco/WhoWorks.text)

Help=$(echo "                                 ~Help Menu:                                    ~______________________________________________________________________________~|./Assign [Category]       | To add yourself to add yourself to that category |~|./Assign add [Category]   | To add that Category to the list                 |~|./Assign remove [Category]| To remove a project all together		      |~|./Assign who              | To view who is working on the project            |~|./Assign remove	   | To remove youself from all projects	      |~|./Assign help             | To view this menu                                |~|./Assign                  | To view who is working on the project            |~ \===========================================================================/" | tr '~' '\n')

if [ $# -lt 1 ]
then
	echo "$Contents" | tr '-' '\n' | tr ',' ' '

elif [ $# -eq 1 ]
then
	#take their user name and add it to category
	if [ "$1" == "who" ]
	then
		echo "$Contents" | tr '-' '\n' | tr ',' ' '
	elif [ "$1" == "help" ]
	then
		echo "$Help"
		echo "Commit projects to this repository;"
		echo "www/hg/project/thegame-fall2016"
	elif [ "$1" == "remove" ]
	then
		Remove=$(echo "$Contents" | grep $USER) # Grabs all instinces of the user
		Contents=$(echo "$Contents" | grep -v $USER)
		Line=$(echo "$Remove"|  wc -l)
		while [ "$Line" -gt 0 ]
		do
			Addon=$(echo "$Remove" | head -$Line | tail -1 | tr ',' '\n' | grep -v "$USER" | tr '\n' ',' | sed 's/,,/,/')
			Contents=$(echo "$Contents~$Addon"| tr '~' '\n')
			Line=$(echo "$Line -1" | bc)
		done
		echo "$Contents" > /home/mzarnoch/src/daco/WhoWorks.text
	else # For adding self to category
		search=$(echo "$Contents" | grep -c "$1")
		if [ $search -eq 1 ]
		then
			Addon=$(echo "$Contents" | grep "$1")
			Addon=$(echo "$Addon,$USER")
			Contents=$(echo "$Contents" | grep -v "$1")
			Contents=$(echo "$Contents~$Addon" | tr '~' '\n')
			echo "$Contents" > /home/mzarnoch/src/daco/WhoWorks.text # Updates the file with the new list
		else
			echo "Error: Class '$1' not in list! Suggest adding it"
			echo "Try who to view project page"
		fi
	fi
elif [ $# -eq 2 ]
then
	if [ $1 == "add" ] # Have to check and see if the person is specifying the add command
	then
		echo "-$2:" >> /home/mzarnoch/src/daco/WhoWorks.text
		echo "$2 added to project page!"
	elif [ $1 == "remove" ] # Have to see if the person is specifying the remove command
	then
		Line=$(echo "$Contents" | grep -c $2)
		if [ $Line -eq 1 ]
		then
			Contents=$(echo "$Contents" | grep -v $2)
			echo "$Contents" > /home/mzarnoch/src/daco/WhoWorks.text # Update the file
		else
			echo "Error: Project name not readable. Try help"
		fi

	else
		echo "Error: '$1' not recognized as a command. Try help"
	fi

else # Person put too many arguements in
	echo "Error: Too many arguments!"
	echo "$Help"
fi
